# Generated by Django 4.2.6 on 2023-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
