# Generated by Django 4.2.6 on 2023-10-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_temperature', '0002_temperature_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 21, 34, 59, 909573)),
        ),
    ]
