# Generated by Django 5.0.6 on 2024-07-06 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_temperature', '0005_sensors_delete_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='gsr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 21, 40, 18, 197778)),
        ),
    ]
